### ISSUE TITLE
syntax error occurring in James

### ISSUE THREAD

**Issue by nicholasf** [floere/james#7]
Hi, 

I thought I'd try write a very simple dialog.

I encountered this error starting it up:

```
andromeda:ada-cms nicholas$ james test_dialog.rb 
<internal:lib/rubygems/custom_require>:29:in `require': /Users/nicholas/.rvm/gems/ruby-1.9.2-p0/gems/james-0.5.0/lib/james/inputs/audio.rb:31: syntax error, unexpected tLABEL (SyntaxError)
      def speechRecognizer sender, didRecognizeCommand: command
                                                       ^
/Users/nicholas/.rvm/gems/ruby-1.9.2-p0/gems/james-0.5.0/lib/james/inputs/audio.rb:47: syntax error, unexpected keyword_end, expecting $end
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /Users/nicholas/.rvm/gems/ruby-1.9.2-p0/gems/james-0.5.0/lib/james.rb:17:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /Users/nicholas/.rvm/gems/ruby-1.9.2-p0/gems/james-0.5.0/aux/james/cli.rb:1:in `<top (required)>'
```

The code was written in one minute.

```
James.dialog do
  hear 'run tests' => :tests

  state :tests do
    # hear ['What time is it?', 'And now?'] => :time
    # into { time = Time.now; "It is currently #{time.hour} #{time.min}." }
    system('trake spec')
    exit {} # Optional, listed for completeness.
  end
end
```

**Comment by floere** [comment]
Hi Nicholas,

The error you got is when James is not run with MacRuby. Did you "rvm use macruby" before running it?

Cool idea with the tests.

```
James.dialog do
  hear 'run tests' => :tests

  state :tests do
    hear 'run tests'
    into { system('rake spec') }
  end
end
```

This dialog will execute `rake spec` when it hears "run tests".

Cheers,
   Florian

**Comment by nicholasf** [comment]
Ah hey,

Yes, thanks, I'll try with macruby soon. trake is an alias I run for rake RAILS_ENV=test

Cheers,
Nick

**Comment by floere** [comment]
Great! I updated the README to more clearly state that one needs to use MacRuby.
